### ISSUE TITLE
Missing Endpoint (Product and Search Feature)

### ISSUE THREAD

**Issue by AlienWolfX** [FrancisCodex/eshop-fg1#10]
Kulangan ug code sa 'admin/products' @JC-E-L 
<br />
https://github.com/FrancisCodex/eshop-fg1/commit/d3ffb1a97b16a8563ec60212d09c833dfc669b3c#diff-569490f072c727f9e24ac431f5ad6f4d870154dc43391d920435682ce480812eR523

![image](https://github.com/user-attachments/assets/d697df89-0638-45e2-b905-07990310b0a1)

**Comment by JC-E-L** [comment]
Nag ingon ba si sir sainyo nga maka create ug product ang admin? Kay mao
man jud dapat na dra nga code. Kay ang among na sabtan ra sa kay admin kay
igo ra sya maka update and delete ug mga products kay naa sa seller nga
role man jud ang maka create ug product.

**Comment by JC-E-L** [comment]
Ay oh sakto diay mb² ako rang e update ron

**Comment by AlienWolfX** [comment]
> Nag ingon ba si sir sainyo nga maka create ug product ang admin?

Wala man hinoon, pero ang login nag ask siya kay ngano naa daw login sa products

**Comment by AlienWolfX** [comment]
Tuod inyoha create kay mu return siyag blank, Status is 200 pero walay ma utro sa database kadto latest db inyo gigamit?

**Comment by JC-E-L** [comment]
E check sa connect.php daw katong bag o man nga database among gamit

**Comment by JC-E-L** [comment]
Akong gi test ang nga routes dri sa amo ron okay raman mo gana man tanan
basin wala ra na connect ug tarong ang database

**Comment by JC-E-L** [comment]
Na push na nako sa among branch ang update nga code tan awa lang sa
routes.php naa na digto ang code sa admin/products. Pasensya karon ra nako
na bantayan

**Comment by AlienWolfX** [comment]
> Akong gi test ang nga routes dri sa amo ron okay raman mo gana man tanan basin wala ra na connect ug tarong ang database

Working na siya bro, sainyo login man diay na route mukuha ug token ka-abi ko sa auth na service.

**Comment by AlienWolfX** [comment]
> Na push na nako sa among branch ang update nga code tan awa lang sa routes.php naa na digto ang code sa admin/products. Pasensya karon ra nako na bantayan

Noted, Thank you

**Comment by JC-E-L** [comment]
Sige² pag ingon ra if naay problem saamo
