### ISSUE TITLE
Need e merge 

### ISSUE THREAD

**Issue by AlienWolfX** [FrancisCodex/eshop-fg1#11]
@FrancisCodex pa merge ko ani bro naay modifications sa 6.1 nga gikan sa **Shopping Cart and CheckOut** na wala na add sa 6.2 

[IT113-Version-6.1-Mysql.sql.txt](https://github.com/user-attachments/files/18051641/IT113-Version-6.1-Mysql.sql.txt)

**Comment by FrancisCodex** [comment]
So mag add rako og new SQL bro? 6.3 na?

**Comment by AlienWolfX** [comment]
> So mag add rako og new SQL bro? 6.3 na?

Yes bro

**Comment by FrancisCodex** [comment]
done na @AlienWolfX

**Comment by AlienWolfX** [comment]
Naay problem bro @FrancisCodex 
![image](https://github.com/user-attachments/assets/3d35e086-0b3c-463f-acdc-b89207a08c71)

**Comment by FrancisCodex** [comment]
check daw karon

> Naay problem bro @FrancisCodex ![image](https://private-user-images.githubusercontent.com/60495687/393611055-3d35e086-0b3c-463f-acdc-b89207a08c71.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM2NzEzODQsIm5iZiI6MTczMzY3MTA4NCwicGF0aCI6Ii82MDQ5NTY4Ny8zOTM2MTEwNTUtM2QzNWUwODYtMGIzYy00NjNmLWFjZGMtYjg5MjA3YTA4YzcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA4VDE1MTgwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3NTIwZDdiNzU1ZmMxZDA4MmFmOGZhZDkyNGUzZGY5OGI5MzYzODg4NDVjODg1YjA3MTZkZTM2MTNjOTNmOTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.GIox61jTfFbCiEsjbr5HQmVpzMzwLRVANuFLV7IGTmA)

**Comment by FrancisCodex** [comment]
ayy wait lang sa naay typo bro sensiya na lipat lang ko wait

**Comment by FrancisCodex** [comment]
@AlienWolfX Okay na fix na ang kanang imong issue and successful nasad sa akong machine pag import sa db file

**Comment by AlienWolfX** [comment]
Goods na bro @FrancisCodex Salamat
